name: 'GitHub Action for ktlint'
description: 'A tool to enforce Kotlin style and conventions'
author: 'Yutaro Muta'
inputs:
  xml-path:
    description: 'The file path of the XML lint report. Support glob patterns. e.g `build/*.xml`'
    required: true
  follow-symbolic-links:
     description: 'Indicates whether to follow symbolic links'
     default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'blue'
