name: 'GitHub Action for ktlint'
description: 'A tool to enforce Kotlin style and conventions'
author: 'yutailang0119'
inputs:
  report-path:
    description: 'The lint report file path. Support glob patterns. e.g `build/*.xml`'
    required: true
  follow-symbolic-links:
     description: 'Indicates whether to follow symbolic links'
     default: true
  ignore-warnings:
    description: 'Ignore Lint Warnings'
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'blue'
